# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: AwsAPI.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import AwsAPI_pb2


class S3Base(abc.ABC):

    @abc.abstractmethod
    async def GetObjects(self, stream: 'grpclib.server.Stream[AwsAPI_pb2.GetObjectsRequest, AwsAPI_pb2.ObjectReply]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/AwsAPI.S3/GetObjects': grpclib.const.Handler(
                self.GetObjects,
                grpclib.const.Cardinality.UNARY_UNARY,
                AwsAPI_pb2.GetObjectsRequest,
                AwsAPI_pb2.ObjectReply,
            ),
        }


class S3Stub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.GetObjects = grpclib.client.UnaryUnaryMethod(
            channel,
            '/AwsAPI.S3/GetObjects',
            AwsAPI_pb2.GetObjectsRequest,
            AwsAPI_pb2.ObjectReply,
        )
