name: benchamark

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

env:
  service: greeter_service


jobs:
#  benchmark:
#    runs-on: ubuntu-latest
#    name: run grpc servers benchmark
#
#    strategy:
#      matrix:
#        server_type:
#          - sync_server_max_worker_1
#          - sync_server_max_worker_50
#          - async_server
#          - async_server_wtih_uvloop
#        rps:
#          - 1
#          - 10
#          - 25
#          - 50
#          - 100
#          - 200
#        service:
#          - greeter_service
#          - aws_s3_service
#          - mongo_service
#        include:
#            - server_type: sync_server_max_worker_1
#              cmd: sync_server.py -w 1
#            - server_type: sync_server_max_worker_50
#              cmd: sync_server.py -w 50
#            - server_type: async_server
#            - server_type: async_server_wtih_uvloop
#            - service: greeter_service
#              dir: computing/greeter_service
#            - service: aws_s3_service
#              dir: network/aws_s3_service
#            - service: mongo_service
#              dir: network/mongo_service
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: '3.8'
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#      - name: Run server
#        run: |
#          cd src/hellow_server && |
#          nohup python ${{ matrix.cmd }} & |
#          cd ../.. && |
#          . run_benchmark.sh ${{ matrix.server_type }} ./request_data/${{ matrix.dir }}_rps_${{ matrix.rps }}.json ./results/${{ matrix.dir }}
  benchmark:
    runs-on: ubuntu-latest
    name: run grpc servers benchmark

    strategy:
      matrix:
        server_type:
          - sync_server_max_worker_1
          - sync_server_max_worker_50
          - async_server
          - async_server_wtih_uvloop
        rps:
          - 1
          - 10
          - 25
          - 50
          - 100
          - 200
        service:
          - greeter_service
#          - aws_s3_service
#          - mongo_service
        include:
            - server_type: sync_server_max_worker_1
              cmd: sync_server.py -w 1
            - server_type: sync_server_max_worker_50
              cmd: sync_server.py -w 50
            - server_type: async_server
            - server_type: async_server_wtih_uvloop
            - service: greeter_service
              dir: computing/greeter_service
#            - service: aws_s3_service
#              dir: network/aws_s3_service
#            - service: mongo_service
#              dir: network/mongo_service

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run server
        run: |
          cd src/hellow_server && |
          nohup python ${{ matrix.cmd }} & |
          cd ../.. && |
          . run_benchmark.sh ${{ matrix.server_type }} ./request_data/${{ matrix.dir }}_rps_${{ matrix.rps }}.json ./results/${{ matrix.dir }}
